server:
  port: 8080
spring:
  application:
    name: "audit-event-service"
  kafka:
    consumer:
      # bootstrap-servers: kafka.home.net:9092
      bootstrap-servers: kafka-server:29092
      group-id: idp-events-consumers
      auto-offset-reset: latest #earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # MySQL connection properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    #url: jdbc:mysql://localhost:3306/swissid_idp_logs
    #url: jdbc:mysql://localhost:3309/swissid_idp
    #url: jdbc:mysql://172.25.0.11:3306/swissid
    url: jdbc:mysql://memsql:3306/swissid

  # Log JPA queries
  # Comment this in production
  jpa:
    show-sql: true

  # Drop and create new tables (create, create-drop, validate, update)
  # Only for testing purpose - comment this in production
  hibernate:
    ddl-auto: create

  # Hibernate SQL dialect
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

  endpoint:
    health:
      show-details: "always"

  metrics:
    tags:
      application: ${spring.application.name}
